Fixed an issue with SIGINT trap on older zsh versions

diff --git a/functions/__apollo_load_utilities b/functions/__apollo_load_utilities
--- a/functions/__apollo_load_utilities
+++ b/functions/__apollo_load_utilities
@@ -92,6 +92,23 @@ __apollo_sanitize() {
 
 }
 
+__apollo_trap_int() {
+
+  # Trap handling is different on older ZSH versions, and need to use function trap in order to preserve return code
+  # Using a list trap for newer ZSH versions as function trap caused issues with other ZSH plugins
+  if ((__APOLLO_LEGACY_TRAP==0)); then
+    trap "zle-line-finish; __APOLLO_EXIT_CODE=130; __apollo_run_prompt; return 130;" INT
+  else
+    TRAPINT(){
+      zle-line-finish
+      __APOLLO_EXIT_CODE=130
+      __apollo_run_prompt
+      return $((128 + $1))
+    }
+  fi
+
+}
+
 __apollo_load_utilities() {};
 
 __apollo_load_utilities "$@"
